In [35]:
import numpy as np
import pandas as pd

# Titanic Data Preprocessing Project

## Steps:
- Data Cleaning
- Handling Missing Values
- Encoding
- Feature Scaling
- Feature Engineering

In [36]:
df=pd.read_csv('tested.csv')

In [37]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [38]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [39]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df

/tmp/ipykernel_12577/2368695939.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,NaN,C

In [40]:
df.drop('Cabin',axis=1,inplace=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.50000,0,0,330911,7.8292,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.00000,1,0,363272,7.0000,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.00000,0,0,240276,9.6875,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.00000,0,0,315154,8.6625,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.00000,1,1,3101298,12.2875,S
...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,30.27259,0,0,A.5. 3236,8.0500,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.00000,0,0,PC 17758,108.9000,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.50000,0,0,SOTON/O.Q. 3101262,7.2500,S
416,1308,0,3,"Ware, Mr. Frederick",male,30.27259,0,0,359309,8.0500,S
417,1309,0,3,"Peter, Master. Michael J",male,30.27259,1,1,2668,22.3583,C

In [41]:
df = pd.get_dummies(df, columns=['Sex', 'Embarked'],dtype=int)
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,892,0,3,"Kelly, Mr. James",34.50000,0,0,330911,7.8292,0,1,0,1,0
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",47.00000,1,0,363272,7.0000,1,0,0,0,1
2,894,0,2,"Myles, Mr. Thomas Francis",62.00000,0,0,240276,9.6875,0,1,0,1,0
3,895,0,3,"Wirz, Mr. Albert",27.00000,0,0,315154,8.6625,0,1,0,0,1
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",22.00000,1,1,3101298,12.2875,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",30.27259,0,0,A.5. 3236,8.0500,0,1,0,0,1
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",39.00000,0,0,PC 17758,108.9000,1,0,1,0,0
415,1307,0,3,"Saether, Mr. Simon Sivertsen",38.50000,0,0,SOTON/O.Q. 3101262,7.2500,0,1,0,0,1
416,1308,0,3,"Ware, Mr. Frederick",30.27259,0,0,359309,8.0500,0,1,0,0,1
417,1309,0,3,"Peter, Master. Michael J",30.27259,1,1,2668,22.3583,0,1,1,0,0

In [42]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', 'Fare']])
df

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,892,0,3,"Kelly, Mr. James",0.452723,0,0,330911,0.015282,0,1,0,1,0
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",0.617566,1,0,363272,0.013663,1,0,0,0,1
2,894,0,2,"Myles, Mr. Thomas Francis",0.815377,0,0,240276,0.018909,0,1,0,1,0
3,895,0,3,"Wirz, Mr. Albert",0.353818,0,0,315154,0.016908,0,1,0,0,1
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",0.287881,1,1,3101298,0.023984,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",0.396975,0,0,A.5. 3236,0.015713,0,1,0,0,1
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",0.512066,0,0,PC 17758,0.212559,1,0,1,0,0
415,1307,0,3,"Saether, Mr. Simon Sivertsen",0.505473,0,0,SOTON/O.Q. 3101262,0.014151,0,1,0,0,1
416,1308,0,3,"Ware, Mr. Frederick",0.396975,0,0,359309,0.015713,0,1,0,0,1
417,1309,0,3,"Peter, Master. Michael J",0.396975,1,1,2668,0.043640,0,1,1,0,0

In [43]:
df.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)
df

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0,3,0.452723,0,0,0.015282,0,1,0,1,0
1,1,3,0.617566,1,0,0.013663,1,0,0,0,1
2,0,2,0.815377,0,0,0.018909,0,1,0,1,0
3,0,3,0.353818,0,0,0.016908,0,1,0,0,1
4,1,3,0.287881,1,1,0.023984,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
413,0,3,0.396975,0,0,0.015713,0,1,0,0,1
414,1,1,0.512066,0,0,0.212559,1,0,1,0,0
415,0,3,0.505473,0,0,0.014151,0,1,0,0,1
416,0,3,0.396975,0,0,0.015713,0,1,0,0,1
417,0,3,0.396975,1,1,0.043640,0,1,1,0,0

In [44]:
df['FamilySize'] = df['SibSp'] + df['Parch']
df

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,FamilySize
0,0,3,0.452723,0,0,0.015282,0,1,0,1,0,0
1,1,3,0.617566,1,0,0.013663,1,0,0,0,1,1
2,0,2,0.815377,0,0,0.018909,0,1,0,1,0,0
3,0,3,0.353818,0,0,0.016908,0,1,0,0,1,0
4,1,3,0.287881,1,1,0.023984,1,0,0,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...
413,0,3,0.396975,0,0,0.015713,0,1,0,0,1,0
414,1,1,0.512066,0,0,0.212559,1,0,1,0,0,0
415,0,3,0.505473,0,0,0.014151,0,1,0,0,1,0
416,0,3,0.396975,0,0,0.015713,0,1,0,0,1,0
417,0,3,0.396975,1,1,0.043640,0,1,1,0,0,2